version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 30s
      retries: 3
    env_file: .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - calendar-network

  goose:
      build:
        context: ../.
        dockerfile: build/goose/Dockerfile
      command: ["goose", "--dir=/migrations", "postgres", "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable", "up"]
      depends_on:
        postgres:
          condition: service_healthy
      volumes:
        - ./../migrations:/migrations

      networks:
        - calendar-network

volumes:
 pgdata:
      driver: local

networks:
    calendar-network:
      driver: bridge
