version: "3.9"
services:
   postgres:
      image: postgres:14-alpine
      environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - 5431:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
      driver: local
