[logger]
level = "info"

[storage]
type = "sql"
dsn = "postgres://admin:pgpswd@localhost:5431/db?sslmode=disable"

[queue]
type = "rmq"
dsn = "amqp://guest:guest@localhost:5672"
exchange = "calendar"
exchangeType = "direct"
queue = "notifications"