[logger]
level = "info"

[HttpServ]
host = "127.0.0.1"
port = "8088"

[GrpsServ]
host = "127.0.0.1"
port = "12000"

[storage]
type = "memory"
dsn = "postgres://admin:pgpswd@localhost:5431/db?sslmode=disable"