[logger]
level = "info"

[HttpServ]
host = "0.0.0.0"
port = "8088"

[GrpsServ]
host = "0.0.0.0"
port = "12000"

[storage]
type = "memory"
dsn = "postgres://admin:pgpswd@postgres:5431/db?sslmode=disable"