[logger]
level = "info"

[storage]
type = "sql"
dsn = "postgres://admin:pgpswd@postgres:5431/db?sslmode=disable"

[queue]
type = "rmq"
dsn = "amqp://guest:guest@rabbit:5672"
queue = "notifications"

[ticker]
interval = "60s"